### ISSUE TITLE
add DOI to existing paper and change to 2024 pub date

### ISSUE THREAD

**Issue by nickreich** [reichlab/reichlab.github.io#223] opened 2024-12-18 19:40 UTC
https://doi.org/10.1093/jrsssa/qnae136

**Comment by micokoch** [comment] 2024-12-19 14:55
Hi @nickreich and @mmkerr - sorry, I hadn't noticed that Melissa was assigned to this. I addressed it in PR #224 - but the build is failing. As far as I can tell, the problem is in the `bundle exec rake collect && build` procedures and is unrelated to the changes I made.

The only slightly different procedure I adopted for this update is that I uploaded a copy of the pdf file directly to the folder for these since the link is only for people with access to the publication. From previous tests, it should work, although I couldn't test it in this build.

**Comment by micokoch** [comment] 2024-12-19 17:58
Update: the problem was fixed - I should have read the error message more carefully. It is because the publication has a colon, which is not allowed. So, I put it inside quotation marks and it worked. The pdf file also works.

Once merged, this issue can be closed.

**Closed as completed** 2024-12-20 14:08 UTC
